import { ICourseData } from "@/lib/mockcourses/CourseMock";

export const mockCourses: ICourseData[] = [
  // Inglés Intensivo B1
  {
    _id: "eng-int-b1",
    languageToLearn: "English",
    title: "Inglés Intensivo B1",
    subTitle: "Avanza rápido con clases intensivas",
    price: "180€",
    hoursPerWeek: "8h",
    longDesc:
      "Curso intensivo de inglés para nivel B1, diseñado para mejorar rápidamente comprensión, expresión oral y escrita.",
    maxPeople: "10",
    duration: "4 semanas",
    format: "Online",
    level: "B1",
    requirements: "Nivel B1 certificado o experiencia previa",
    learningObjetives:
      "Mejorar comprensión auditiva y expresión oral; ampliar vocabulario y gramática avanzada.",
    modules:
      "Módulo 1: Gramática avanzada\nMódulo 2: Conversación práctica\nMódulo 3: Comprensión auditiva y lectura",
    technicalRequirements:
      "Ordenador o tablet con cámara y micrófono; conexión a internet estable",
    modality: "Intensive",
    startDate: "2025-11-05",
    access: "Plataforma online propia",
    support: "Tutor personal vía chat y email",
    gains: "Nivel B1 consolidado y habilidades comunicativas reforzadas",
    certificate: "Certificado de asistencia y progreso",
    imageUrl: "/assets/intensiveGroup.png",
    createdAt: new Date(),
    updatedAt: new Date(),
    topCourses: true,
    status: "inProgress",
    slug: "eng-int-b1",
  },

  // Inglés Semi-intensivo B1
  {
    _id: "eng-semi-b1",
    languageToLearn: "English",
    title: "Inglés Semi-intensivo B1",
    subTitle: "Mejora tu inglés sin saturarte",
    price: "120€",
    hoursPerWeek: "4h",
    longDesc:
      "Curso semi-intensivo de inglés B1, ideal para reforzar el idioma mientras compaginas otras actividades.",
    maxPeople: "15",
    duration: "6 semanas",
    format: "Online",
    level: "B1",
    requirements: "Nivel B1 certificado o experiencia previa",
    learningObjetives:
      "Refuerzo de gramática y vocabulario, mejora de conversación y comprensión.",
    modules:
      "Módulo 1: Gramática intermedia\nMódulo 2: Conversación guiada\nMódulo 3: Comprensión escrita y auditiva",
    technicalRequirements:
      "Ordenador o tablet con cámara y micrófono; conexión a internet estable",
    modality: "SemiIntensive",
    startDate: "2025-11-10",
    access: "Plataforma online propia",
    support: "Tutor personal vía chat y email",
    gains: "Mayor fluidez y confianza en conversaciones B1",
    certificate: "Certificado de progreso",
    imageUrl: "/assets/intensiveGroup.png",
    createdAt: new Date(),
    updatedAt: new Date(),
    topCourses: true,
    status: "soon",
    slug: "eng-semi-b1",
  },

  // Inglés Privado (nivel adaptado)
  {
    _id: "eng-privado",
    languageToLearn: "English",
    title: "Inglés Privado",
    subTitle: "Clases personalizadas al nivel del estudiante",
    price: "220€",
    hoursPerWeek: "6h",
    longDesc:
      "Curso privado de inglés, adaptado al nivel y objetivos del estudiante, con enfoque totalmente personalizado.",
    maxPeople: "1",
    format: "Online",
    learningObjetives:
      "Mejorar todas las competencias lingüísticas según necesidades personales.",
    modules: "Módulos adaptados al estudiante",
    modality: "Private",
    access: "Plataforma online propia",
    support: "Tutor personal vía chat y email",
    certificate: "Certificado de progreso personalizado",
    imageUrl: "/assets/onetoone.png",
    createdAt: new Date(),
    updatedAt: new Date(),
    topCourses: true,
    status: "pending",
    slug: "eng-privado",
  },

  // Español Intensivo B1
  {
    _id: "esp-int-b1",
    languageToLearn: "Spanish",
    title: "Español Intensivo B1",
    subTitle: "Aprende español de forma intensiva",
    price: "180€",
    hoursPerWeek: "8h",
    longDesc:
      "Curso intensivo de español B1, diseñado para consolidar habilidades de comunicación rápidamente.",
    maxPeople: "10",
    duration: "4 semanas",
    format: "Online",
    level: "B1",
    requirements: "Nivel B1 certificado o experiencia previa",
    learningObjetives: "Refuerzo de gramática, vocabulario y fluidez oral.",
    modules:
      "Módulo 1: Gramática avanzada\nMódulo 2: Conversación práctica\nMódulo 3: Comprensión auditiva y lectura",
    technicalRequirements:
      "Ordenador o tablet con cámara y micrófono; conexión a internet estable",
    modality: "Intensive",
    startDate: "2025-11-05",
    access: "Plataforma online propia",
    support: "Tutor personal vía chat y email",
    gains: "Nivel B1 consolidado y habilidades comunicativas reforzadas",
    certificate: "Certificado de asistencia y progreso",
    imageUrl: "/assets/intensiveGroup.png",
    createdAt: new Date(),
    updatedAt: new Date(),
    topCourses: true,
    status: "pending",
    slug: "esp-int-b1",
  },

  // Español Semi-intensivo B1
  {
    _id: "esp-semi-b1",
    languageToLearn: "Spanish",
    title: "Español Semi-intensivo B1",
    subTitle: "Aprende español sin saturarte",
    price: "120€",
    hoursPerWeek: "4h",
    longDesc:
      "Curso semi-intensivo de español B1, ideal para reforzar tus competencias mientras realizas otras actividades.",
    maxPeople: "15",
    duration: "6 semanas",
    format: "Online",
    level: "B1",
    requirements: "Nivel B1 certificado o experiencia previa",
    learningObjetives: "Refuerzo de gramática, vocabulario y fluidez oral.",
    modules:
      "Módulo 1: Gramática intermedia\nMódulo 2: Conversación guiada\nMódulo 3: Comprensión escrita y auditiva",
    technicalRequirements:
      "Ordenador o tablet con cámara y micrófono; conexión a internet estable",
    modality: "SemiIntensive",
    startDate: "2025-11-10",
    access: "Plataforma online propia",
    support: "Tutor personal vía chat y email",
    gains: "Mayor fluidez y confianza en conversaciones B1",
    certificate: "Certificado de progreso",
    imageUrl: "/assets/intensiveGroup.png",
    createdAt: new Date(),
    updatedAt: new Date(),
    topCourses: true,
    status: "soon",
    slug: "esp-semi-b1",
  },

  // Español Privado (nivel adaptado)
  {
    _id: "esp-privado",
    languageToLearn: "Spanish",
    title: "Español Privado",
    subTitle: "Clases personalizadas al nivel del estudiante",
    price: "220€",
    hoursPerWeek: "6h",
    longDesc:
      "Curso privado de español adaptado al nivel y objetivos del estudiante.",
    maxPeople: "1",
    format: "Online",
    learningObjetives:
      "Mejorar todas las competencias lingüísticas según necesidades personales.",
    modules: "Módulos adaptados al estudiante",
    modality: "Private",
    access: "Plataforma online propia",
    support: "Tutor personal vía chat y email",
    certificate: "Certificado de progreso personalizado",
    imageUrl: "/assets/onetoone.png",
    createdAt: new Date(),
    updatedAt: new Date(),
    topCourses: true,
    status: "inProgress",
    slug: "esp-privado",
  },
  {
    _id: "eng-int-b1-2",
    languageToLearn: "English",
    title: "Inglés Intensivo B1 Extra 1",
    subTitle: "Curso intensivo adicional",
    price: "180€",
    hoursPerWeek: "8h",
    longDesc: "Curso intensivo de inglés para nivel B1...",
    maxPeople: "10",
    duration: "4 semanas",
    format: "Online",
    level: "B1",
    learningObjetives: "Refuerzo de todas las competencias B1",
    modules: "Módulo 1\nMódulo 2\nMódulo 3",
    modality: "Intensive",
    imageUrl: "/assets/intensiveGroup.png",
    createdAt: new Date(),
    updatedAt: new Date(),
    topCourses: false,
    status: "inProgress",
    slug: "eng-int-b1-2",
  },
  {
    _id: "eng-int-b1-3",
    languageToLearn: "English",
    title: "Inglés Intensivo B1 Extra 2",
    subTitle: "Curso intensivo adicional",
    price: "180€",
    hoursPerWeek: "8h",
    longDesc: "Curso intensivo de inglés para nivel B1...",
    maxPeople: "10",
    duration: "4 semanas",
    format: "Online",
    level: "B1",
    learningObjetives: "Refuerzo de todas las competencias B1",
    modules: "Módulo 1\nMódulo 2\nMódulo 3",
    modality: "Intensive",
    imageUrl: "/assets/intensiveGroup.png",
    createdAt: new Date(),
    updatedAt: new Date(),
    topCourses: false,
    status: "pending",
    slug: "eng-int-b1-3",
  },
  {
    _id: "eng-int-b1-4",
    languageToLearn: "English",
    title: "Inglés Intensivo B1 Extra 3",
    subTitle: "Curso intensivo adicional",
    price: "180€",
    hoursPerWeek: "8h",
    longDesc: "Curso intensivo de inglés para nivel B1...",
    maxPeople: "10",
    duration: "4 semanas",
    format: "Online",
    level: "B1",
    learningObjetives: "Refuerzo de todas las competencias B1",
    modules: "Módulo 1\nMódulo 2\nMódulo 3",
    modality: "Intensive",
    imageUrl: "/assets/intensiveGroup.png",
    createdAt: new Date(),
    updatedAt: new Date(),
    topCourses: false,
    status: "inProgress",
    slug: "eng-int-b1-4",
  },
  {
    _id: "eng-int-b1-5",
    languageToLearn: "English",
    title: "Inglés Intensivo B1 Extra 4",
    subTitle: "Curso intensivo adicional",
    price: "180€",
    hoursPerWeek: "8h",
    longDesc: "Curso intensivo de inglés para nivel B1...",
    maxPeople: "10",
    duration: "4 semanas",
    format: "Online",
    level: "B1",
    learningObjetives: "Refuerzo de todas las competencias B1",
    modules: "Módulo 1\nMódulo 2\nMódulo 3",
    modality: "Intensive",
    imageUrl: "/assets/intensiveGroup.png",
    createdAt: new Date(),
    updatedAt: new Date(),
    topCourses: false,
    status: "inProgress",
    slug: "eng-int-b1-5",
  },

  // -------------------
  // Cursos adicionales Español (topCourses: false)
  {
    _id: "esp-int-b1-2",
    languageToLearn: "Spanish",
    title: "Español Intensivo B1 Extra 1",
    subTitle: "Curso intensivo adicional",
    price: "180€",
    hoursPerWeek: "8h",
    longDesc: "Curso intensivo de español B1...",
    maxPeople: "10",
    duration: "4 semanas",
    format: "Online",
    level: "B1",
    learningObjetives: "Refuerzo de todas las competencias B1",
    modules: "Módulo 1\nMódulo 2\nMódulo 3",
    modality: "Intensive",
    imageUrl: "/assets/intensiveGroup.png",
    createdAt: new Date(),
    updatedAt: new Date(),
    topCourses: false,
    status: "soon",
    slug: "esp-int-b1-2",
  },
  {
    _id: "esp-int-b1-3",
    languageToLearn: "Spanish",
    title: "Español Intensivo B1 Extra 2",
    subTitle: "Curso intensivo adicional",
    price: "180€",
    hoursPerWeek: "8h",
    longDesc: "Curso intensivo de español B1...",
    maxPeople: "10",
    duration: "4 semanas",
    format: "Online",
    level: "B1",
    learningObjetives: "Refuerzo de todas las competencias B1",
    modules: "Módulo 1\nMódulo 2\nMódulo 3",
    modality: "Intensive",
    imageUrl: "/assets/intensiveGroup.png",
    createdAt: new Date(),
    updatedAt: new Date(),
    topCourses: false,
    status: "inProgress",
    slug: "esp-int-b1-3",
  },
  {
    _id: "esp-int-b1-4",
    languageToLearn: "Spanish",
    title: "Español Intensivo B1 Extra 3",
    subTitle: "Curso intensivo adicional",
    price: "180€",
    hoursPerWeek: "8h",
    longDesc: "Curso intensivo de español B1...",
    maxPeople: "10",
    duration: "4 semanas",
    format: "Online",
    level: "B1",
    learningObjetives: "Refuerzo de todas las competencias B1",
    modules: "Módulo 1\nMódulo 2\nMódulo 3",
    modality: "Intensive",
    imageUrl: "/assets/intensiveGroup.png",
    createdAt: new Date(),
    updatedAt: new Date(),
    topCourses: false,
    status: "inProgress",
    slug: "esp-int-b1-4",
  },
  {
    _id: "esp-int-b1-5",
    languageToLearn: "Spanish",
    title: "Español Intensivo B1 Extra 4",
    subTitle: "Curso intensivo adicional",
    price: "180€",
    hoursPerWeek: "8h",
    longDesc: "Curso intensivo de español B1...",
    maxPeople: "10",
    duration: "4 semanas",
    format: "Online",
    level: "B1",
    learningObjetives: "Refuerzo de todas las competencias B1",
    modules: "Módulo 1\nMódulo 2\nMódulo 3",
    modality: "Intensive",
    imageUrl: "/assets/intensiveGroup.png",
    createdAt: new Date(),
    updatedAt: new Date(),
    topCourses: false,
    status: "soon",
    slug: "esp-int-b1-5",
  },
];
